### ISSUE TITLE
Pure Function API

### ISSUE THREAD

**Issue by shuhei** [kuy/redux-merge-reducers#6]
I think it's more idiomatic to just have a function to merge reducers like `combileReducers`.

```js
export default combineReducers({
  foo, bar, sharedreducer: mergeReducers(sharedReducer, extraReducer)
});
```

It can be achieved by something like:

```js
function mergeReducers(...reducers) {
  const initialState = reducers.reduce(
    (acc, reducer) => Object.assign(acc, reducer(undefined, {})),
    {}
  );
  return (state = initialState, action) => reducers.reduce(
    (acc, reducer) => reducer(acc, action),
    state
  );
}
```

**Comment by shuhei** [comment]
Of course the initial state can be created lazily as in the current implementation.

**Comment by kuy** [comment]
Interesting, thank you! I It's difficult to decide changing API or create it as yet another merge-reducer. If I write two API docs, two usage examples, two type defs, it should be separated into two packages.

**Comment by shuhei** [comment]
Makes sense. Closing the issue :-)
